name: Manually Dispatch Workflows

on:
  workflow_dispatch:
    # NOTE: boolean inputs are still actually strings
    # See: https://github.com/actions/runner/issues/1483
    inputs:
      lints:
        description: 'Run Lints'
        type: boolean
        required: true
        default: true
      build_linux:
        description: 'Build/Test Linux'
        type: boolean
        required: true
        default: true
      build_macos_intel:
        description: 'Build/Test Mac (Intel)'
        type: boolean
        required: true
        default: false
      build_macos_arm:
        description: 'Build/Test Mac (Arm)'
        type: boolean
        required: true
        default: false
      build_windows:
        description: 'Build/Test Win'
        type: boolean
        required: true
        default: false
      save_cache:
        description: 'Save Cache'
        type: boolean
        required: true
        default: false

jobs:
  lint_all:
    name: Lint All
    if: ${{ github.event.inputs.lints == 'true' }}
    uses: ./.github/workflows/reusable_lint.yml
    with:
      SAVE_CACHE: ${{ github.event.inputs.save_cache == 'true' }}
    secrets:
      CALLER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux:
    name: Build/Test Linux
    if: ${{ github.event.inputs.build_linux == 'true' }}
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      SAVE_CACHE: ${{ github.event.inputs.save_cache == 'true' }}
      PLATFORM: linux
    secrets:
      CALLER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    name: Build/Test Windows
    if: ${{ github.event.inputs.build_windows == 'true'}}
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      SAVE_CACHE: ${{ github.event.inputs.save_cache == 'true' }}
      PLATFORM: windows
    secrets:
      CALLER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_mac_arm:
    name: Build/Test Mac (Arm)
    if: ${{ github.event.inputs.build_macos_arm == 'true' }}
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      SAVE_CACHE: ${{ github.event.inputs.save_cache == 'true' }}
      PLATFORM: macos-arm
    secrets:
      CALLER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_mac_intel:
    name: Build/Test Mac (Intel)
    if: ${{ github.event.inputs.build_macos_intel == 'true' }}
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      SAVE_CACHE: ${{ github.event.inputs.save_cache == 'true' }}
      PLATFORM: macos-intel
    secrets:
      CALLER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
